spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gridge_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#  redis:
#    host: localhost
#    port: 6379
